name: SSH Example

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-know-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Run SSH command
        run: ssh ubuntu@ip-172-31-80-57 "echo 'Hello from SSH command'"
